version: '3'
services:
  db:
    container_name: postgres-quizhub
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quizhub



  redis:
    container_name: "quizhub-redis-v1"
    image: redis:latest
    ports:
      - "6377:6379"
    restart: always

volumes:
  redis_data: